#ifndef NOXAM_NOXAMOSVERSIONCHECKER_HXX
#define NOXAM_NOXAMOSVERSIONCHECKER_HXX

#define NOXAM_PRODUCT_PROFESSIONAL 0x00000030
#define NOXAM_VER_SUITE_WH_SERVER 0x00008000
#define _CRT_OBSOLETE_NO_WARNINGS

typedef void(WINAPI *NXMPGSNSI)(LPSYSTEM_INFO);
typedef BOOL(WINAPI *NXMPGPI)(DWORD, DWORD, DWORD, DWORD, DWORD);

bool NoxamWindowsVersionname(char *NxmStr, int NxmBufferSize);

#endif NOXAM_NOXAMOSVERSIONCHECKER_HXX
